CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS organizations (id UUID PRIMARY KEY, name TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, organization_id UUID REFERENCES organizations(id), email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK (role IN ('manager','employee')), created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS data_sources (id UUID PRIMARY KEY, organization_id UUID REFERENCES organizations(id), type TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'disconnected', credentials JSONB, last_sync_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS customers (id UUID PRIMARY KEY, organization_id UUID REFERENCES organizations(id), canonical_name TEXT NOT NULL, email TEXT, phone TEXT, created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS invoices (id UUID PRIMARY KEY, organization_id UUID REFERENCES organizations(id), customer_id UUID REFERENCES customers(id), source_id UUID REFERENCES data_sources(id), external_id TEXT NOT NULL, invoice_number TEXT, amount NUMERIC(18,2) NOT NULL, currency TEXT NOT NULL, status TEXT, invoice_date DATE, due_date DATE);
CREATE TABLE IF NOT EXISTS payments (id UUID PRIMARY KEY, organization_id UUID REFERENCES organizations(id), customer_id UUID REFERENCES customers(id), invoice_id UUID REFERENCES invoices(id), source_id UUID REFERENCES data_sources(id), external_id TEXT NOT NULL, amount NUMERIC(18,2) NOT NULL, currency TEXT NOT NULL, payment_date DATE);
CREATE TABLE IF NOT EXISTS sales (id UUID PRIMARY KEY, organization_id UUID REFERENCES organizations(id), customer_id UUID REFERENCES customers(id), source_id UUID REFERENCES data_sources(id), external_id TEXT NOT NULL, amount NUMERIC(18,2) NOT NULL, currency TEXT NOT NULL, sale_date DATE);
CREATE TABLE IF NOT EXISTS search_documents (id UUID PRIMARY KEY, organization_id UUID REFERENCES organizations(id), source_id UUID REFERENCES data_sources(id), entity_type TEXT, entity_id UUID, content TEXT NOT NULL, metadata JSONB, embedding vector(1536), created_at TIMESTAMPTZ DEFAULT now());
CREATE INDEX IF NOT EXISTS search_documents_fts_idx ON search_documents USING gin (to_tsvector('simple', content));
CREATE TABLE IF NOT EXISTS sync_jobs (id UUID PRIMARY KEY, source_id UUID REFERENCES data_sources(id), status TEXT NOT NULL, records_seen INTEGER DEFAULT 0, records_written INTEGER DEFAULT 0, error TEXT, started_at TIMESTAMPTZ DEFAULT now(), finished_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS query_logs (id UUID PRIMARY KEY, organization_id UUID REFERENCES organizations(id), user_id UUID REFERENCES users(id), question TEXT NOT NULL, sources_used JSONB, latency_ms INTEGER, result JSONB, confidence NUMERIC(5,4), created_at TIMESTAMPTZ DEFAULT now());
